### ISSUE TITLE
Error log

### ISSUE THREAD

**Issue by LucidAPs** [DownThePark/SetHome#2]
[16:18:47 ERROR]: Could not pass event PlayerRespawnEvent to SetHome v4.0
java.lang.IllegalArgumentException: Name cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.14.3.jar:git-Paper-125]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.getWorld(CraftServer.java:1078) ~[patched_1.14.3.jar:git-Paper-125]
        at org.bukkit.Bukkit.getWorld(Bukkit.java:525) ~[patched_1.14.3.jar:git-Paper-125]
        at me.downthepark.sethome.SetHomeEvents.onPlayerRespawn(SetHomeEvents.java:28) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor38.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.3.jar:git-Paper-125]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.3.jar:git-Paper-125]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.3.jar:git-Paper-125]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.3.jar:git-Paper-125]
        at net.minecraft.server.v1_14_R1.PlayerList.moveToWorld(PlayerList.java:671) ~[patched_1.14.3.jar:git-Paper-125]
        at net.minecraft.server.v1_14_R1.PlayerList.moveToWorld(PlayerList.java:596) ~[patched_1.14.3.jar:git-Paper-125]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2102) ~[patched_1.14.3.jar:git-Paper-125]
        at net.minecraft.server.v1_14_R1.PacketPlayInClientCommand.a(SourceFile:31) ~[patched_1.14.3.jar:git-Paper-125]
        at net.minecraft.server.v1_14_R1.PacketPlayInClientCommand.a(SourceFile:8) ~[patched_1.14.3.jar:git-Paper-125]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.3.jar:git-Paper-125]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.3.jar:git-Paper-125]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.3.jar:git-Paper-125]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.3.jar:git-Paper-125]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.3.jar:git-Paper-125]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[patched_1.14.3.jar:git-Paper-125]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[patched_1.14.3.jar:git-Paper-125]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[patched_1.14.3.jar:git-Paper-125]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:979) ~[patched_1.14.3.jar:git-Paper-125]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[patched_1.14.3.jar:git-Paper-125]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

**Comment by DownThePark** [comment]
Fixed in SetHome 4.1
